version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      house-library-net:
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin ping' ]
      interval: 10s
      timeout: 2s
      retries: 10

  house-library-app:
    image: house-library
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysqldb
    networks:
      house-library-net:
    restart: on-failure
  
networks:
  house-library-net:
