version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: house_library
      MYSQL_CHARSET: utf8
    networks:
      house-library-net:
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2_data.sql

  app:
    image: house-library
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
    networks:
      house-library-net:
    restart: on-failure
  
networks:
  house-library-net:
