version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      house-library-net:

  house-library-app:
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      house-library-net:
    restart: on-failure
  
networks:
  house-library-net:
