version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: house_library
    volumes:
      - "./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
      house-library-net:

  house-library-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      house-library-net:
    restart: on-failure
  
networks:
  house-library-net:
