INSERT INTO `category`
VALUES (1, 'Matematyka'),
       (2, 'Fizyka'),
       (3, 'Elektrotechnika'),
       (4, 'Elektronika'),
       (5, 'Automatyka'),
       (6, 'Robotyka'),
       (7, 'Informatyka');

INSERT INTO `subcategory`
VALUES (1, 'Algebra', 1),
       (2, 'Analiza', 1),
       (3, 'Fizyka Ogólna', 2),
       (4, 'Mechanika', 2),
       (5, 'Elektromagnetyzm', 2),
       (6, 'Teoria pola', 2),
       (7, 'Mechanika kwantowa', 2),
       (8, 'Teoria względności', 2),
       (9, 'Fizyka Współczesna', 2),
       (10, 'Teoria obwodów', 3),
       (11, 'Maszyny elektryczne', 3),
       (12, 'Metrologia elektryczna', 3),
       (13, 'Układy analogowe i cyfrowe', 4),
       (14, 'Technika cyfrowa', 4),
       (15, 'Mikrokontrolery i mikrokomputery', 4),
       (16, 'Teoria sterowania', 5),
       (17, 'Sterowniki PLC', 5),
       (18, 'Robotyka Ogólna', 6),
       (19, 'Informatyka Ogólna', 7);

INSERT INTO `author`
VALUES (1, 'Julian', 'Klukowski'),
       (2, 'Ireneusz', 'Nabiałek'),
       (3, 'Andrzej', 'Białynicki-Birula'),
       (4, 'Aleksiej', 'Kostrikin'),
       (5, 'Franciszek', 'Leja'),
       (6, 'Ryszard', 'Rudnicki'),
       (7, 'Witold', 'Kołodziej'),
       (8, 'Walter', 'Rudin'),
       (9, 'Grigorij', 'Fichtenholz'),
       (10, 'Robert', 'Kowalczyk'),
       (11, 'Kamil', 'Niedziałomski'),
       (12, 'Cezary', 'Obczyński'),
       (13, 'Andrzej', 'Palczewski'),
       (14, 'Lawrence', 'Evans'),
       (15, 'James', 'Stewart'),
       (16, 'Igor', 'Sawieliew'),
       (17, 'Jerzy', 'Massalski'),
       (18, 'Michalina', 'Massalska'),
       (19, 'Walter', 'Thirring'),
       (20, 'Richard', 'Feynman'),
       (21, 'Robert', 'Leighton'),
       (22, 'Matthew', 'Sands'),
       (23, 'Robert', 'Resnick'),
       (24, 'David', 'Halliday'),
       (25, 'Jerzy', 'Leyko'),
       (26, 'John', 'Taylor'),
       (27, 'Lew', 'Landau'),
       (28, 'Jewgienij M.', 'Lifszyc'),
       (29, 'Wojciech', 'Rubinowicz'),
       (30, 'Wojciech', 'Królikowski'),
       (31, 'Józef', 'Nizioł'),
       (32, 'David J.', 'Griffiths'),
       (33, 'Zygmunt', 'Piątek'),
       (34, 'Paweł', 'Jabłoński'),
       (35, 'John David', 'Jackson'),
       (36, 'Krzysztof', 'Meissner'),
       (37, 'Steven', 'Weinberg'),
       (38, 'Iwo', 'Białynicki-Birula'),
       (39, 'Stanisław', 'Kryszewski'),
       (40, 'Darrel F.', 'Shroeter'),
       (41, 'Ramamurti', 'Shankar'),
       (42, 'Marek', 'Cieplak'),
       (43, 'Jerzy', 'Kamiński'),
       (44, 'Władymir B.', 'Bierestecki'),
       (45, 'Lew P.', 'Pitajewski'),
       (46, 'Richard L.', 'Liboff'),
       (47, 'James D.', 'Bjorken'),
       (48, 'Sidney D.', 'Drell'),
       (49, 'Leonard I.', 'Schiff'),
       (50, 'Paul T.', 'Matthews'),
       (51, 'Bernard F.', 'Schutz'),
       (52, 'James B.', 'Hartle'),
       (53, 'Albert', 'Einstein'),
       (54, 'Donald H.', 'Perkins'),
       (55, 'Stanisław', 'Bolkowski'),
       (56, 'Stanisław', 'Osowski'),
       (57, 'Krzysztof', 'Siwek'),
       (58, 'Michał', 'Śmiałek'),
       (59, 'Tadeusz', 'Glinka'),
       (60, 'Lech', 'Grzesiak'),
       (61, 'Bartłomiej', 'Ufnalski'),
       (62, 'Arkadiusz', 'Kaszewski'),
       (63, 'Antoni', 'Plamitzer'),
       (64, 'Władysław', 'Latek'),
       (65, 'Zdzisław', 'Grunwald'),
       (66, 'Jacek', 'Przepiórkowski'),
       (67, 'Andrzej', 'Dębowski'),
       (68, 'Augustyn', 'Chwaleba'),
       (69, 'Maciej', 'Poniński'),
       (70, 'Andrzej', 'Siedlecki'),
       (71, 'Andrzej', 'Filipkowski'),
       (72, 'Zbigniew', 'Nosal'),
       (73, 'Jerzy', 'Baranowski'),
       (74, 'Grzegorz', 'Czajkowski'),
       (75, 'Bogusław', 'Kalinowski'),
       (76, 'Józef', 'Boksa'),
       (77, 'Jerzy', 'Pasierbiński'),
       (78, 'Mirosław', 'Rusek'),
       (79, 'Bogdan', 'Moeschke'),
       (80, 'Grzegorz', 'Płoszajski'),
       (81, 'Piotr', 'Majdak'),
       (82, 'Piotr', 'Świstak'),
       (83, 'Wiesław', 'Marciniak'),
       (84, 'Ulrich', 'Tietze'),
       (85, 'Christoph', 'Schenk'),
       (86, 'Marian P.', 'Kaźmierkowski'),
       (87, 'Jerzy T.', 'Matysik'),
       (88, 'Barbara', 'Pióro'),
       (89, 'Marek', 'Pióro'),
       (90, 'Paul', 'Horowitz'),
       (91, 'Winfield', 'Hill'),
       (92, 'Marcin', 'Olszewski'),
       (93, 'Barry', 'Willkson'),
       (94, 'Józef', 'Kalisz'),
       (95, 'Wiesław', 'Traczyk'),
       (96, 'Piotr', 'Misiurewicz'),
       (97, 'Marek', 'Grzybek'),
       (98, 'Marian', 'Łakomy'),
       (99, 'Jan', 'Zabrodzki'),
       (100, 'Jan', 'Pieńkos'),
       (101, 'Janusz', 'Turczyński'),
       (102, 'Ryszard', 'Krzyżanowski'),
       (103, 'William', 'Stallings'),
       (104, 'Krzysztof', 'Paprocki'),
       (105, 'Maciej', 'Szumski'),
       (106, 'Aleksander', 'Kurczyk'),
       (107, 'Andrzej', 'Pawluczuk'),
       (108, 'Elliot', 'Williams'),
       (109, 'Tomasz', 'Francuz'),
       (110, 'Michael', 'Margolis'),
       (111, 'Brian', 'Jepson'),
       (112, 'Nicholas R.', 'Weldin'),
       (113, 'Simon', 'Monk'),
       (114, 'Tadeusz', 'Kaczorek'),
       (115, 'Andrzej', 'Dzieliński'),
       (116, 'Włodzimierz', 'Dąbrowski'),
       (117, 'Rafał', 'Łopatka'),
       (118, 'Jacek', 'Kabziński'),
       (119, 'Andrzej', 'Słota'),
       (120, 'Dominika', 'Śniegulska-Grądzka'),
       (121, 'Maciej', 'Szafarczyk'),
       (122, 'Rafał', 'Wypysiński'),
       (123, 'Zdzisław', 'Bubnicki'),
       (124, 'Marek', 'Żelazny'),
       (125, 'Przemysław', 'Mosiołek'),
       (126, 'Stefan', 'Węgrzyn'),
       (127, 'Jerzy', 'Kasprzyk'),
       (128, 'Robert', 'Sałat'),
       (129, 'Krzysztof', 'Korpyt'),
       (130, 'Paweł', 'Obstawski'),
       (131, 'Bogdan', 'Broel-Plater'),
       (132, 'Janusz', 'Kwaśniewski'),
       (133, 'Jerzy', 'Honczarenko'),
       (134, 'Piotr', 'Dutkiewicz'),
       (135, 'Waldemar', 'Wróblewski'),
       (136, 'Krzysztof', 'Kozłowski'),
       (137, 'Mordechai', 'Ben-Ari'),
       (138, 'Francesco', 'Mondada'),
       (139, 'John J.', 'Craig'),
       (140, 'J. Glenn', 'Brookshear'),
       (141, 'Dennis', 'Brylow'),
       (142, 'Abraham', 'Silberschatz'),
       (143, 'Peter B.', 'Galvin'),
       (144, 'Greg', 'Gagne'),
       (145, 'Krzysztof', 'Barteczko'),
       (146, 'Matthew', 'Hickey'),
       (147, 'Jennifer', 'Arcuri'),
       (148, 'Sylwester', 'Walczak'),
       (149, 'Chris', 'Bernhardt'),
       (150, 'Gynvael', 'Coldwind'),
       (151, 'Marcin', 'Szeliga'),
       (152, 'Russell', 'Bradford'),
       (153, 'Brian', 'Ward');

INSERT INTO `book`
VALUES (1, 'LOW', 'Algebra dla studentów', 1),
       (2, 'LOW', 'Algebra', 1),
       (3, 'LOW', 'Wstęp do algebry', 1),
       (4, 'LOW', 'Rachunek różniczkowy i całkowy', 2),
       (5, 'LOW', 'Wykłady z analizy matematycznej', 2),
       (6, 'LOW', 'Analiza matematyczna', 2),
       (7, 'LOW', 'Analiza funkcjonalna', 2),
       (8, 'LOW', 'Rachunek różniczkowy i całkowy', 2),
       (9, 'LOW', 'Podstawy analizy matematycznej', 2),
       (10, 'LOW', 'Całki. Metody rozwiązywania zadań', 2),
       (11, 'LOW', 'Równania różniczkowe zwyczajne', 2),
       (12, 'LOW', 'Równania różniczkowe cząstkowe', 2),
       (13, 'LOW', 'Calculus', 2),
       (14, 'LOW', 'Wykłady z fizyki I-III', 3),
       (15, 'LOW', 'Fizyka dla inżynierów I-II', 3),
       (16, 'LOW', 'Fizyka matematyczna', 3),
       (17, 'LOW', 'Feynmana wykłady z fizyki', 3),
       (18, 'LOW', 'Fizyka I-II', 3),
       (19, 'LOW', 'Mechanika ogólna', 4),
       (20, 'LOW', 'Mechanika klasyczna', 4),
       (21, 'LOW', 'Mechanika', 4),
       (22, 'LOW', 'Mechanika teoretyczna', 4),
       (23, 'LOW', 'Metodyka rozwiązywania zadań z mechaniki ', 4),
       (24, 'LOW', 'Podstawy elektrodynamiki', 5),
       (25, 'LOW', 'Podstawy teorii pola elektromagnetycznego', 5),
       (26, 'LOW', 'Elektrodynamika klasyczna', 5),
       (27, 'LOW', 'Teoria pola', 6),
       (28, 'LOW', 'Klasyczna teoria pola', 6),
       (29, 'LOW', 'Teoria pól kwantowych I-III', 6),
       (30, 'LOW', 'Wstęp do teorii pól kwantowych', 6),
       (31, 'LOW', 'Mechanika kwantowa', 7),
       (32, 'LOW', 'Wstęp do mechaniki kwantowej', 7),
       (33, 'LOW', 'Mechanika kwantowa', 7),
       (34, 'LOW', 'Teoria kwantów', 7),
       (35, 'LOW', 'Elektrodynamika kwantowa', 7),
       (36, 'LOW', 'Wstęp do mechaniki kwantowej', 7),
       (37, 'LOW', 'Mechanika kwantowa', 7),
       (38, 'LOW', 'Relatywistyczna teoria kwantów', 7),
       (39, 'LOW', 'Mechanika kwantowa', 7),
       (40, 'LOW', 'Wstęp do mechaniki kwantowej', 7),
       (41, 'LOW', 'Wstęp do ogólnej teorii względności', 8),
       (42, 'LOW', 'Grawitacja', 8),
       (43, 'LOW', 'Istota teorii względności', 8),
       (44, 'LOW', 'Wstęp do fizyki wysokich energii', 9),
       (45, 'LOW', 'Teoria obwodów', 10),
       (46, 'LOW', 'Teoria obwodów', 10),
       (47, 'LOW', 'Maszyny elektryczne i transformatory', 11),
       (48, 'LOW', 'Sterowanie napędów elektrycznych', 11),
       (49, 'LOW', 'Maszyny elektryczne', 11),
       (50, 'LOW', 'Maszyny elektryczne w pytaniach i odpowiedziach', 11),
       (51, 'LOW', 'Napęd elektryczny', 11),
       (52, 'LOW', 'Silniki elektryczne w praktyce elektronika', 11),
       (53, 'LOW', 'Automatyka. Napęd elektryczny', 11),
       (54, 'LOW', 'Elektryczny napęd trakcyjny', 11),
       (55, 'LOW', 'Maszyny elektryczne wzbudzane magnesami trwałymi', 11),
       (56, 'LOW', 'Metrologia elektryczna', 12),
       (57, 'LOW', 'Układy analogowe i cyfrowe', 13),
       (58, 'LOW', 'Układy elektroniczne I-III', 13),
       (59, 'LOW', 'Analogowe układy elektroniczne', 13),
       (60, 'LOW', 'Elementy i układy elektroniczne w pytaniach i odpowiedziach', 13),
       (61, 'LOW', 'Podstawy elektroniki', 13),
       (62, 'LOW', 'Przyrządy półprzewodnikowe i układy scalone', 13),
       (63, 'LOW', 'Układy półprzewodnikowe', 13),
       (64, 'LOW', 'Wprowadzenie do elektroniki i energoelektroniki', 13),
       (65, 'LOW', 'Podstawy elektroniki', 13),
       (66, 'LOW', 'Sztuka elektroniki', 13),
       (67, 'LOW', 'Elektronika dla informatyków', 13),
       (68, 'LOW', 'Układy cyfrowe', 14),
       (69, 'LOW', 'Podstawy elektroniki cyfrowej', 14),
       (70, 'LOW', 'Układy cyfrowe automatyki', 14),
       (71, 'LOW', 'Podstawy techniki cyfrowej', 14),
       (72, 'LOW', 'Półprzewodnikowe układy logiczne TTL', 14),
       (73, 'LOW', 'Cyfrowe układy scalone TTL', 14),
       (74, 'LOW', 'Układy scalone TTL w systemach cyfrowych', 14),
       (75, 'LOW', 'Układy cyfrowe. Podstawy teoretyczne i metody syntezy', 14),
       (76, 'LOW', 'Układy mikroprocesorowe', 15),
       (77, 'LOW', 'Organizacja i architektura systemu komputerowego I-II', 15),
       (78, 'LOW', 'Układy mikroprocesorowe', 15),
       (79, 'LOW', 'Podstawy techniki mikroprocesorowej', 15),
       (80, 'LOW', 'Mikrokontrolery STM32 w praktyce', 15),
       (81, 'LOW', 'Mikrokontrolery STM32 w systemach sterowania i regulacji', 15),
       (82, 'LOW', 'Mikrokontrolery STM32 dla początkujących', 15),
       (83, 'LOW', 'Sztuka programowania mikrokontrolerów AVR. Podstawy', 15),
       (84, 'LOW', 'Programowanie układów AVR dla praktyków', 15),
       (85, 'LOW', 'Język C dla mikrokontrolerów AVR', 15),
       (86, 'LOW', 'Arduino', 15),
       (87, 'LOW', 'Raspberry Pi. Receptury', 15),
       (88, 'LOW', 'Podstawy teorii sterowania', 16),
       (89, 'LOW', 'Teoria sterowania', 16),
       (90, 'LOW', 'Sterowanie procesami ciągłymi', 16),
       (91, 'LOW', 'Podstawy układów sterowań cyfrowych i komputerowych', 16),
       (92, 'LOW', 'Teoria i algorytmy sterowania', 16),
       (93, 'LOW', 'Automatyka. Podstawy teorii', 16),
       (94, 'LOW', 'Automatyka. Technika regulacji', 16),
       (95, 'LOW', 'Podstawy automatyki', 16),
       (96, 'LOW', 'Projektowanie nieliniowych układów sterowania', 16),
       (97, 'LOW', 'Podstawy automatyki', 16),
       (98, 'LOW', 'Programowanie sterowników przemysłowych', 17),
       (99, 'LOW', 'Wstęp do programowania sterowników PLC', 17),
       (100, 'LOW', 'Układy wykorzystujące sterowniki PLC', 17),
       (101, 'LOW', 'Sterowniki PLC w praktyce inżynierskiej', 17),
       (102, 'LOW', 'Inteligentny dom i inne systemy sterowania w 100 przykładach', 17),
       (103, 'LOW', 'Roboty przemysłowe', 18),
       (104, 'LOW', 'Modelowanie i sterowanie robotów', 18),
       (105, 'LOW', 'Elementy robotyki', 18),
       (106, 'LOW', 'Wprowadzenie do robotyki', 18),
       (107, 'LOW', 'Informatyka w ogólnym zarysie', 19),
       (108, 'LOW', 'Podstawy systemów operacyjnych I-II', 19),
       (109, 'LOW', 'Java. Uniwersalne techniki programowania', 19),
       (110, 'LOW', 'Warsztat hakera', 19),
       (111, 'LOW', 'Nowoczesne Django', 19),
       (112, 'LOW', 'Obliczenia kwantowe dla każdego', 19),
       (113, 'LOW', 'Zrozumieć programowanie', 19),
       (114, 'LOW', 'Praktyczne uczenie maszynowe', 19),
       (115, 'LOW', 'Podstawy sieci komputerowych', 19),
       (116, 'LOW', 'Jak działa Linux', 19);


INSERT INTO `author_book`
VALUES (1, 1),
       (2, 1),
       (3, 2),
       (4, 3),
       (5, 4),
       (6, 5),
       (7, 6),
       (8, 7),
       (9, 8),
       (8, 9),
       (10, 10),
       (11, 10),
       (12, 10),
       (13, 11),
       (14, 12),
       (15, 13),
       (16, 14),
       (17, 15),
       (18, 15),
       (19, 16),
       (20, 17),
       (21, 17),
       (22, 17),
       (23, 18),
       (24, 18),
       (25, 19),
       (26, 20),
       (27, 21),
       (28, 21),
       (29, 22),
       (30, 22),
       (31, 23),
       (32, 24),
       (33, 25),
       (34, 25),
       (35, 26),
       (27, 27),
       (28, 27),
       (36, 28),
       (37, 29),
       (38, 30),
       (39, 31),
       (32, 32),
       (40, 32),
       (41, 33),
       (38, 34),
       (42, 34),
       (43, 34),
       (44, 35),
       (28, 35),
       (45, 35),
       (46, 36),
       (27, 37),
       (28, 37),
       (47, 38),
       (48, 38),
       (49, 39),
       (50, 40),
       (51, 41),
       (52, 42),
       (53, 43),
       (54, 44),
       (55, 45),
       (56, 46),
       (57, 46),
       (58, 46),
       (59, 47),
       (60, 48),
       (61, 48),
       (62, 48),
       (63, 49),
       (64, 50),
       (65, 51),
       (66, 52),
       (67, 53),
       (67, 54),
       (59, 55),
       (68, 56),
       (69, 56),
       (70, 56),
       (71, 57),
       (72, 58),
       (73, 58),
       (74, 58),
       (75, 58),
       (76, 59),
       (77, 60),
       (78, 60),
       (68, 61),
       (79, 61),
       (80, 61),
       (81, 61),
       (82, 61),
       (83, 62),
       (84, 63),
       (85, 63),
       (86, 64),
       (87, 64),
       (88, 65),
       (89, 65),
       (90, 66),
       (91, 66),
       (92, 67),
       (93, 68),
       (94, 69),
       (95, 70),
       (96, 71),
       (96, 72),
       (97, 72),
       (98, 73),
       (99, 73),
       (100, 74),
       (101, 74),
       (95, 75),
       (102, 76),
       (103, 77),
       (96, 78),
       (96, 79),
       (104, 80),
       (105, 81),
       (106, 82),
       (107, 83),
       (108, 84),
       (109, 85),
       (110, 86),
       (111, 86),
       (112, 86),
       (113, 87),
       (114, 88),
       (115, 88),
       (116, 88),
       (117, 88),
       (118, 89),
       (119, 90),
       (120, 91),
       (121, 91),
       (122, 91),
       (123, 92),
       (67, 93),
       (67, 94),
       (124, 95),
       (118, 96),
       (125, 96),
       (126, 97),
       (127, 98),
       (128, 99),
       (129, 99),
       (130, 99),
       (131, 100),
       (132, 101),
       (132, 102),
       (133, 103),
       (134, 104),
       (135, 104),
       (136, 104),
       (137, 105),
       (138, 105),
       (139, 106),
       (140, 107),
       (141, 107),
       (142, 108),
       (143, 108),
       (144, 108),
       (145, 109),
       (146, 110),
       (147, 110),
       (148, 111),
       (149, 112),
       (150, 113),
       (151, 114),
       (152, 115),
       (153, 116);
